name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: 17 }
      - uses: android-actions/setup-android@v3
      - run: sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"
      - name: Inject Channel Key
        run: sed -i "s/YOUR_CHANNEL_KEY_HERE/${{ secrets.CHANNEL_KEY }}/" app/src/main/java/com/atcltd/zendeskapp/MainActivity.kt
      - uses: gradle/gradle-build-action@v3
        with: { gradle-version: "8.5", arguments: wrapper }
      - run: ./gradlew assembleDebug
      - uses: actions/upload-artifact@v4
        with: { name: app-debug, path: app/build/outputs/apk/debug/app-debug.apk }
